[build]
  command = "node build.js"
  publish = "build"

[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_CDA_TOKEN = "w7sdyslol3fu"
  CONTENTFUL_SPACE = "w7sdyslol3fu"
